#!/bin/bash
set -e

# Include all installer scripts
for tool_installer in tools/*; do
  # shellcheck disable=SC1090
  source "${tool_installer}"
done

install_all=""
install_list=""
tools_file="tools.txt"
available_tools="$(cat ${tools_file})"

# echo command combines multiple lines into one
# shellcheck disable=SC2005
available_tools_help="$(echo "$(cat ${tools_file})")"

cache_dir="/var/cache/winit"
commons_cache="commons_installed"
commons_cache_path="${cache_dir}/${commons_cache}"

display_help() {
  cat << EOF

USAGE: $(basename "$0") [OPTIONS] [TOOL...]

COPYRIGHT:  Copyright (c) 2019 Ogun Acik

DESCRIPTION:
  Provisioner for tools I use on my development workstation.
  Supported platforms : linux/amd64
  Supported distros   : Debian{9,10} Ubuntu{16,18} Centos{7,}
  Available tools     : ${available_tools_help}

OPTIONS:
  -h - Show this help and exit
  -a - Install all tools listed in ${tools_file}. No other arguments required.
       If you want to ignore any tool in ${tools_file}, comment it out with hash sign (#).

EXAMPLES:
  $ sudo ./$(basename "$0") go docker cloudsdk
    # Install go, docker and cloudsdk

  $ sudo ./$(basename "$0") ansible
    # Install ansible

  $ sudo ./$(basename "$0") -a
    # Install all available tools: (${available_tools_help})

EOF
}

get_distribution() {
  lsb_dist=""

  if [ -r /etc/os-release ]; then
    # shellcheck disable=SC1091
    source /etc/os-release
    id="${ID}"
    version_id_inline=$(echo "${VERSION_ID}" | cut -d "." -f 1)
  fi

  lsb_dist="$(echo "${id}_${version_id_inline}" | tr '[:upper:]' '[:lower:]')"
  echo "${lsb_dist}"
}

dist=$(get_distribution)

# Parse and evaluate options
while [[ $# -gt 0 ]]; do
  case "${1}" in
  -h)
    display_help
    exit 0
    ;;
  -a)
    install_all=1
    shift
    break
    ;;
  *)
    break
    ;;
  esac
  shift
done

# Define installation list
if [[ -n "${install_all}" ]]; then
  install_list="${available_tools}"
else
  install_list="${*}"
fi

# Invalidate cache for common packages older than 1 day.
if [[ -f "${commons_cache}" ]]; then
  find "${cache_dir}" -name "${commons_cache}" -mtime +1 -delete > /dev/null
fi

# Install common required packages
if [[ -n "${install_list}" ]]; then
  if [[ -f "${commons_cache_path}" ]]; then
    echo "Common packages already installed. Skipping..."
  else
    common_packages="${dist}_common"
    "${common_packages}"
    mkdir -p "${cache_dir}"
    touch "${commons_cache_path}"
  fi
fi

# Install tool(s)
for pkg in ${install_list}; do
  if [[ "${pkg:0:1}" == "#" ]]; then
    echo "Skipping ${pkg:1}"
  else
    dist_installer="${dist}_${pkg}"
    if command -v "${dist_installer}" > /dev/null; then
      "${dist_installer}"
    else
      echo
      echo "ERROR: ${pkg} doesn't exist in available tools."
      echo "Run ./$(basename "$0") -h for help."
      echo
      exit 1
    fi
  fi
done
