#!/bin/bash

# Include functions
# shellcheck disable=SC1091
source functions/common.sh

# Include tests
# shellcheck disable=SC1091
source test/common.sh

# Include installer scripts
for tool_installer in tools/*; do
  # shellcheck disable=SC1090
  source "${tool_installer}"
done

tools_file="tools.txt"
available_tools="$(cat ${tools_file})"

cache_dir="/var/cache/winit"
commons_cache="commons_installed"
commons_cache_path="${cache_dir}/${commons_cache}"

dist=$(get_distribution)

# Parse and evaluate options
while [[ $# -gt 0 ]]; do
  case "${1}" in
  -h)
    display_help
    exit 0
    ;;
  -a)
    install_all=1
    shift
    break
    ;;
  *)
    break
    ;;
  esac
  shift
done

# Define installation list
if [[ -n "${install_all}" ]]; then
  install_list="${available_tools}"
else
  install_list="${*}"
fi

# Invalidate cache for common packages older than 1 day.
if [[ -f "${commons_cache_path}" ]]; then
  find "${cache_dir}" -name "${commons_cache}" -mtime +1 -delete > /dev/null
fi

# Install requirements packages
set -e

if [[ -n "${install_list}" ]]; then
  if [[ -f "${commons_cache_path}" ]]; then
    print_yellow "Requirements already installed."
    echo
  else
    print_yellow "Installing requirements..."
    common_packages="${dist}_common"
    "${common_packages}" > "${logdir}/common_packages" 2>&1
    mkdir -p "${cache_dir}"
    touch "${commons_cache_path}"
    print_green "Requirements installed successfully."
    echo
  fi
fi

set +e

# Install tool(s)
for pkg in ${install_list}; do
  if [[ "${pkg:0:1}" == "#" ]]; then
    print_yellow "Skipped ${pkg:1}"
  else
    dist_installer="${dist}_${pkg}"
    if command -v "${dist_installer}" > /dev/null; then
      print_yellow "Installing ${pkg}..."
      "${dist_installer}" > "${logdir}/${pkg}.log" 2>&1
      "test_${pkg}"
    else
      echo
      print_red "\nERROR: ${pkg} doesn't exist in available tools."
      print_red "Run ./$(basename "$0") -h for help."
      echo
    fi
  fi
done
