#!/bin/bash

# Include installer scripts
for tool_installer in tools/*; do
  # shellcheck disable=SC1090
  source "${tool_installer}"
done

# Include functions
source functions/common.sh

install_all=""
install_list=""
tools_file="tools.txt"
available_tools="$(cat ${tools_file})"

# echo command combines multiple lines into one
# shellcheck disable=SC2005
available_tools_help="$(echo "$(cat ${tools_file})")"

cache_dir="/var/cache/winit"
commons_cache="commons_installed"
commons_cache_path="${cache_dir}/${commons_cache}"

dist=$(get_distribution)

# Parse and evaluate options
while [[ $# -gt 0 ]]; do
  case "${1}" in
  -h)
    display_help
    exit 0
    ;;
  -a)
    install_all=1
    shift
    break
    ;;
  *)
    break
    ;;
  esac
  shift
done

# Define installation list
if [[ -n "${install_all}" ]]; then
  install_list="${available_tools}"
else
  install_list="${*}"
fi

# Invalidate cache for common packages older than 1 day.
if [[ -f "${commons_cache_path}" ]]; then
  find "${cache_dir}" -name "${commons_cache}" -mtime +1 -delete > /dev/null
fi

# Install common required packages
set -e

if [[ -n "${install_list}" ]]; then
  if [[ -f "${commons_cache_path}" ]]; then
    echo "Common packages already installed. Skipping..."
    echo
  else
    common_packages="${dist}_common"
    "${common_packages}"
    mkdir -p "${cache_dir}"
    touch "${commons_cache_path}"
  fi
fi

set +x

# Install tool(s)
for pkg in ${install_list}; do
  if [[ "${pkg:0:1}" == "#" ]]; then
    echo "Skipping ${pkg:1}"
    echo
  else
    dist_installer="${dist}_${pkg}"
    if command -v "${dist_installer}" > /dev/null; then
      "${dist_installer}"
    else
      echo
      echo "ERROR: ${pkg} doesn't exist in available tools."
      echo "Run ./$(basename "$0") -h for help."
      echo
      exit 1
    fi
  fi
done
