version: 2.0

jobs:
  "debian-stretch":
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: ./winit -a

  "debian-buster":
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run: ./winit -a

  "ubuntu-xenial":
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run: ./winit -a

  "ubuntu-bionic":
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run: ./winit -a

  "centos-7":
    docker:
      - image: centos:7
    steps:
      - checkout
      - run: ./winit -a

  "centos-8":
    docker:
      - image: centos:8
    steps:
      - checkout
      - run: ./winit -a

workflows:
  version: 2
  build:
    jobs:
      - "debian-stretch"
      - "debian-buster"
      - "ubuntu-xenial"
      - "ubuntu-bionic"
      - "centos-7"
      - "centos-8"
